### ISSUE TITLE
怎么修改登录名和密码

### ISSUE THREAD

**Issue by fishingfly** [evanxuhe/skywalking-kubernetes#6]
修改ui中的webapp.xml文件不起作用

**Comment by fishingfly** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui-deployment
  namespace: kube-system
  labels:
    app: skywalking-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-ui
  template:
    metadata:
      labels:
        app: skywalking-ui
    spec:
      containers:
      - name: skywalking-ui
        image: registry.paas/cmss/skywalking-ui:6.1.0
        ports:
        - containerPort: 8080
          name: page
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        env:
        - name: SW_OAP_ADDRESS
          value: skywalking-oap:12800
        - name: security.user.admin.password  #加个环境变量就可以了
          value: 8cDcos11

**Comment by hbstarjason** [comment]
@fishingfly 
非常感谢，测试通过！
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: skywalking
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: apache/skywalking-ui:6.1.0
        ports:
        - containerPort: 8080
          name: page
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        env:
        - name: SW_OAP_ADDRESS
          value: oap:12800
        - name: security.user.admin.password
          value: 8cDcos11
```
