### ISSUE TITLE
测试使用问题

### ISSUE THREAD

**Issue by hbstarjason** [evanxuhe/skywalking-kubernetes#8]
目标：
在原有的item和eureka的两个服务下，新增一个服务为apm-demo（spring boot），期望出现数据和拓扑图。

结果：
无论是单独增加还是注册到原有的eureka服务下，都无法出现预期的数据和拓扑图。

新增服务apm-demo的yaml内容如下：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-demo
  labels:
    app: apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-demo
  template:
    metadata:
      name: apm-demo
      labels:
        app: apm-demo
    spec:
      initContainers:
        - name: sidecar
          image: evanxuhe/skywalking-agent-sidecar:6.1.0 # 容器镜像，包含静态资源文件
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/data/agent", "/sidecar"]
          volumeMounts:
            - name: sidecar
              mountPath: /sidecar
      containers:
        - name: apm-demo
          image: hbstarjason/k8s-example:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -javaagent:/sidecar/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: apm-demo
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap.skywalking.svc.cluster.local:11800
            #- name: EUREKA_HOSTNAME
            #  value: apm-eureka
            #- name: EUREKA_PORT
            #  value: '8761'
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: sidecar
              mountPath: /sidecar
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: apm-demo
  #namespace: skywalking
  labels:
    service: apm-demo
spec:
  type: LoadBalancer
  selector:
    app: apm-demo
  ports:
    - port: 8080
      name: apm-demo
      targetPort: 8080
      #nodePort: 30088
```
